### ISSUE TITLE
[JENKINS-5933] Error Starting Hudson after upgrade

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/subversion-plugin#670]
<p>We have upgraded from Hudson 1.345 to 1.350, and Sonar plugin from 1.3 to 1.4. The log is:</p>

<p>ADVERTENCIA: Skipping a non-existent field revPropSupport<br/>
com.thoughtworks.xstream.converters.reflection.NonExistentFieldException: No such field hudson.scm.SubversionSCM$DescriptorImpl.revPropSupport<br/>
at com.thoughtworks.xstream.converters.reflection.FieldDictionary.field(FieldDictionary.java:106)<br/>
at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldType(PureJavaReflectionProvider.java:152)<br/>
at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:330)<br/>
at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:219)<br/>
at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:174)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)<br/>
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)<br/>
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)<br/>
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)<br/>
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:923)<br/>
at hudson.util.XStream2.unmarshal(XStream2.java:70)<br/>
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:909)<br/>
at hudson.XmlFile.unmarshal(XmlFile.java:148)<br/>
at hudson.model.Descriptor.load(Descriptor.java:551)<br/>
at hudson.scm.SCMDescriptor.load(SCMDescriptor.java:80)<br/>
at hudson.scm.SubversionSCM$DescriptorImpl.<init>(SubversionSCM.java:1563)<br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br/>
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br/>
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br/>
at java.lang.Class.newInstance0(Class.java:355)<br/>
at java.lang.Class.newInstance(Class.java:308)<br/>
at net.java.sezpoz.IndexItem.instance(IndexItem.java:149)<br/>
at hudson.ExtensionFinder$Sezpoz.findExtensions(ExtensionFinder.java:101)<br/>
at hudson.ExtensionList.load(ExtensionList.java:198)<br/>
at hudson.ExtensionList.ensureLoaded(ExtensionList.java:181)<br/>
at hudson.ExtensionList.iterator(ExtensionList.java:112)<br/>
at hudson.model.Hudson.getDescriptorByType(Hudson.java:916)<br/>
at hudson.plugins.sonar.SonarPublisher.getInstallation(SonarPublisher.java:276)<br/>
at hudson.plugins.sonar.SonarPublisher.getSonarUrl(SonarPublisher.java:383)<br/>
at hudson.plugins.sonar.SonarPublisher.getProjectAction(SonarPublisher.java:430)<br/>
at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:75)<br/>
at hudson.maven.MavenModuleSet.updateTransientActions(MavenModuleSet.java:206)<br/>
at hudson.model.AbstractProject.onLoad(AbstractProject.java:232)<br/>
at hudson.maven.MavenModuleSet.onLoad(MavenModuleSet.java:397)<br/>
at hudson.model.Items.load(Items.java:107)<br/>
at hudson.model.Hudson$12.run(Hudson.java:2090)<br/>
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)<br/>
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)<br/>
at hudson.model.Hudson$3.runTask(Hudson.java:649)<br/>
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)<br/>
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:885)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:907)<br/>
at java.lang.Thread.run(Thread.java:619)}</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=adfernandez">adfernandez</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-5933" target="_blank">Error Starting Hudson after upgrade</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/mindless.png" title="mindless's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mindless">mindless</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>component(s)</b>: subversion-plugin
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2010-03-31T08:19:20+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251212-090250
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>We have upgraded from Hudson 1.345 to 1.350, and Sonar plugin from 1.3 to 1.4. The log is:</p>

<p>ADVERTENCIA: Skipping a non-existent field revPropSupport
com.thoughtworks.xstream.converters.reflection.NonExistentFieldException: No such field hudson.scm.SubversionSCM$DescriptorImpl.revPropSupport
        at com.thoughtworks.xstream.converters.reflection.FieldDictionary.field(FieldDictionary.java:106)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldType(PureJavaReflectionProvider.java:152)
        at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:330)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:219)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:174)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:923)
        at hudson.util.XStream2.unmarshal(XStream2.java:70)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:909)
        at hudson.XmlFile.unmarshal(XmlFile.java:148)
        at hudson.model.Descriptor.load(Descriptor.java:551)
        at hudson.scm.SCMDescriptor.load(SCMDescriptor.java:80)
        at hudson.scm.SubversionSCM$DescriptorImpl.&lt;init&gt;(SubversionSCM.java:1563)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at java.lang.Class.newInstance0(Class.java:355)
        at java.lang.Class.newInstance(Class.java:308)
        at net.java.sezpoz.IndexItem.instance(IndexItem.java:149)
        at hudson.ExtensionFinder$Sezpoz.findExtensions(ExtensionFinder.java:101)
        at hudson.ExtensionList.load(ExtensionList.java:198)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:181)
        at hudson.ExtensionList.iterator(ExtensionList.java:112)
        at hudson.model.Hudson.getDescriptorByType(Hudson.java:916)
        at hudson.plugins.sonar.SonarPublisher.getInstallation(SonarPublisher.java:276)
        at hudson.plugins.sonar.SonarPublisher.getSonarUrl(SonarPublisher.java:383)
        at hudson.plugins.sonar.SonarPublisher.getProjectAction(SonarPublisher.java:430)
        at hudson.tasks.BuildStepCompatibilityLayer.getProjectActions(BuildStepCompatibilityLayer.java:75)
        at hudson.maven.MavenModuleSet.updateTransientActions(MavenModuleSet.java:206)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:232)
        at hudson.maven.MavenModuleSet.onLoad(MavenModuleSet.java:397)
        at hudson.model.Items.load(Items.java:107)
        at hudson.model.Hudson$12.run(Hudson.java:2090)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
        at hudson.model.Hudson$3.runTask(Hudson.java:649)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:885)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:907)
        at java.lang.Thread.run(Thread.java:619)}</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>OpenSuse 10.3 Tomcat 6</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>japher:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-5933?focusedId=137499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-137499">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Also receiving this on Ubuntu 9.10 server after upgrading from 1.348 to 1.352.</p>

<p>Looks like this is related to the Subversion SCM plugin, assigning to mindless (as one of the maintainers).</p>

<p>When I enter the Manage Hudson area, I see the message:
"You have data stored in an older format and/or unreadable data."</p>

<p>When I click Manage, I see the following further info:</p>

<p>Type: hudson.scm.SubversionSCM$DescriptorImpl	</p>

<p>Name: Subversion	</p>

<p>Error: NonExistentFieldException: No such field hudson.scm.SubversionSCM$DescriptorImpl.revPropSupport</p>
</pre>
</details>

</ul>
</details>

<p>Also receiving this on Ubuntu 9.10 server after upgrading from 1.348 to 1.352.</p>

<p>Looks like this is related to the Subversion SCM plugin, assigning to mindless (as one of the maintainers).</p>

<p>When I enter the Manage Hudson area, I see the message:<br/>
"You have data stored in an older format and/or unreadable data."</p>

<p>When I click Manage, I see the following further info:</p>

<p>Type: hudson.scm.SubversionSCM$DescriptorImpl	</p>

<p>Name: Subversion	</p>

<p>Error: NonExistentFieldException: No such field hudson.scm.SubversionSCM$DescriptorImpl.revPropSupport</p>
