### ISSUE TITLE
[JENKINS-11897] Subversion 1.36 does not work on Jenkins 1.441

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/subversion-plugin#874]
<p>Subversion 1.36 does not work on Jenkins 1.441. When I run job during updating working copy it fails:</p>

<p>09:38:55  Started by user Oleksandr Popov<br/>
09:38:55  Building on master<br/>
09:38:55  Updating svn://<span class="error">&#91;server-name&#93;</span>/<span class="error">&#91;branch-name&#93;</span><br/>
09:38:59  FATAL: de/regnis/q/sequence/line/QSequenceLineRAData<br/>
09:38:59  java.lang.NoClassDefFoundError: de/regnis/q/sequence/line/QSequenceLineRAData<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.DefaultSVNOptions.createMerger(DefaultSVNOptions.java:561)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.admin.SVNAdminArea.mergeProperties(SVNAdminArea.java:470)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNUpdateEditor.closeFile(SVNUpdateEditor.java:1827)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNUpdateEditor.closeFile(SVNUpdateEditor.java:1231)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNAmbientDepthFilterEditor.closeFile(SVNAmbientDepthFilterEditor.java:141)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNCancellableEditor.closeFile(SVNCancellableEditor.java:141)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNEditModeReader.processCommand(SVNEditModeReader.java:162)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNEditModeReader.driveEditor(SVNEditModeReader.java:232)<br/>
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNRepositoryImpl.update(SVNRepositoryImpl.java:1493)<br/>
09:38:59  	at org.tmatesoft.svn.core.wc.SVNUpdateClient.update(SVNUpdateClient.java:564)<br/>
09:38:59  	at org.tmatesoft.svn.core.wc.SVNUpdateClient.doUpdate(SVNUpdateClient.java:401)<br/>
09:38:59  	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:135)<br/>
09:38:59  	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:136)<br/>
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:787)<br/>
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:768)<br/>
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:752)<br/>
09:38:59  	at hudson.FilePath.act(FilePath.java:783)<br/>
09:38:59  	at hudson.FilePath.act(FilePath.java:765)<br/>
09:38:59  	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:742)<br/>
09:38:59  	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:684)<br/>
09:38:59  	at hudson.model.AbstractProject.checkout(AbstractProject.java:1195)<br/>
09:38:59  	at hudson.model.AbstractBuild$AbstractRunner.checkout(AbstractBuild.java:568)<br/>
09:38:59  	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:457)<br/>
09:38:59  	at hudson.model.Run.run(Run.java:1404)<br/>
09:38:59  	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:481)<br/>
09:38:59  	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
09:38:59  	at hudson.model.Executor.run(Executor.java:238)</p>

<p>I've rolled back to 1.35 and it working fine.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=pxantom">pxantom</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-11897" target="_blank">Subversion 1.36 does not work on Jenkins 1.441</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: subversion-plugin
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2011-11-29T12:55:43+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 0
<li><b>imported</b>: 20251212-090250
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Subversion 1.36 does not work on Jenkins 1.441. When I run job during updating working copy it fails:</p>

<p>09:38:55  Started by user Oleksandr Popov
09:38:55  Building on master
09:38:55  Updating svn://<span class="error">&#91;server-name&#93;</span>/<span class="error">&#91;branch-name&#93;</span>
09:38:59  FATAL: de/regnis/q/sequence/line/QSequenceLineRAData
09:38:59  java.lang.NoClassDefFoundError: de/regnis/q/sequence/line/QSequenceLineRAData
09:38:59  	at org.tmatesoft.svn.core.internal.wc.DefaultSVNOptions.createMerger(DefaultSVNOptions.java:561)
09:38:59  	at org.tmatesoft.svn.core.internal.wc.admin.SVNAdminArea.mergeProperties(SVNAdminArea.java:470)
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNUpdateEditor.closeFile(SVNUpdateEditor.java:1827)
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNUpdateEditor.closeFile(SVNUpdateEditor.java:1231)
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNAmbientDepthFilterEditor.closeFile(SVNAmbientDepthFilterEditor.java:141)
09:38:59  	at org.tmatesoft.svn.core.internal.wc.SVNCancellableEditor.closeFile(SVNCancellableEditor.java:141)
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNEditModeReader.processCommand(SVNEditModeReader.java:162)
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNEditModeReader.driveEditor(SVNEditModeReader.java:232)
09:38:59  	at org.tmatesoft.svn.core.internal.io.svn.SVNRepositoryImpl.update(SVNRepositoryImpl.java:1493)
09:38:59  	at org.tmatesoft.svn.core.wc.SVNUpdateClient.update(SVNUpdateClient.java:564)
09:38:59  	at org.tmatesoft.svn.core.wc.SVNUpdateClient.doUpdate(SVNUpdateClient.java:401)
09:38:59  	at hudson.scm.subversion.UpdateUpdater$TaskImpl.perform(UpdateUpdater.java:135)
09:38:59  	at hudson.scm.subversion.WorkspaceUpdater$UpdateTask.delegateTo(WorkspaceUpdater.java:136)
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.perform(SubversionSCM.java:787)
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:768)
09:38:59  	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:752)
09:38:59  	at hudson.FilePath.act(FilePath.java:783)
09:38:59  	at hudson.FilePath.act(FilePath.java:765)
09:38:59  	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:742)
09:38:59  	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:684)
09:38:59  	at hudson.model.AbstractProject.checkout(AbstractProject.java:1195)
09:38:59  	at hudson.model.AbstractBuild$AbstractRunner.checkout(AbstractBuild.java:568)
09:38:59  	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:457)
09:38:59  	at hudson.model.Run.run(Run.java:1404)
09:38:59  	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:481)
09:38:59  	at hudson.model.ResourceController.execute(ResourceController.java:88)
09:38:59  	at hudson.model.Executor.run(Executor.java:238)</p>

<p>I've rolled back to 1.35 and it working fine.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 1.441 Subversion plugin 1.36</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/evernat.png" title="evernat's avatar" /> evernat:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-11897?focusedId=155930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-155930">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I confirm the issue with the same stack-trace (same environment)</p>
</pre>
</details>

</ul>
</details>

<p>I confirm the issue with the same stack-trace (same environment)</p>
