### ISSUE TITLE
[JENKINS-10771] hudson.util.IOException2: remote file operation failed

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/subversion-plugin#831]
<p>After upgrading jenkins from 1.415 to 1.426 we cannot build anymore any project on our windows node. We get the exception:<br/>
Building remotely on WSJENKINSDEV01<br/>
hudson.util.IOException2: remote file operation failed: d:\Program Files\jenkins_slave\workspace\TASC Workbench at hudson.remoting.Channel@​4f854f85:WSJENKINSDEV01<br/>
	at hudson.FilePath.act(FilePath.java:754)<br/>
	at hudson.FilePath.act(FilePath.java:740)<br/>
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:731)<br/>
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:676)<br/>
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1193)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.checkout(AbstractBuild.java:555)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:443)<br/>
	at hudson.model.Run.run(Run.java:1376)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:230)<br/>
Caused by: java.io.IOException: Remote call on WSJENKINSDEV01 failed<br/>
	at hudson.remoting.Channel.call(Channel.java:677)<br/>
	at hudson.FilePath.act(FilePath.java:747)<br/>
	... 10 more<br/>
Caused by: java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson<br/>
	at hudson.scm.SubversionWorkspaceSelector.syncWorkspaceFormatFromMaster(SubversionWorkspaceSelector.java:85)<br/>
	at hudson.scm.SubversionSCM.createSvnClientManager(SubversionSCM.java:808)<br/>
	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:751)<br/>
	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:738)<br/>
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:1994)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)<br/>
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)<br/>
	at hudson.remoting.Request$2.run(Request.java:287)<br/>
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at hudson.remoting.Engine$1$1.run(Engine.java:60)<br/>
	at java.lang.Thread.run(Unknown Source)</p>

<p>As soon as we rollback, we are able again to build the project.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=lot">lot</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771" target="_blank">hudson.util.IOException2: remote file operation failed</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=recena">recena</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>component(s)</b>: subversion-plugin
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2015-12-13T11:20:17+00:00
<li><b>votes</b>: 37
<li><b>watchers</b>: 37
<li><b>imported</b>: 20251212-090250
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading jenkins from 1.415 to 1.426 we cannot build anymore any project on our windows node. We get the exception:
Building remotely on WSJENKINSDEV01
hudson.util.IOException2: remote file operation failed: d:\Program Files\jenkins_slave\workspace\TASC Workbench at hudson.remoting.Channel@4f854f85:WSJENKINSDEV01
	at hudson.FilePath.act(FilePath.java:754)
	at hudson.FilePath.act(FilePath.java:740)
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:731)
	at hudson.scm.SubversionSCM.checkout(SubversionSCM.java:676)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1193)
	at hudson.model.AbstractBuild$AbstractRunner.checkout(AbstractBuild.java:555)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:443)
	at hudson.model.Run.run(Run.java:1376)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:230)
Caused by: java.io.IOException: Remote call on WSJENKINSDEV01 failed
	at hudson.remoting.Channel.call(Channel.java:677)
	at hudson.FilePath.act(FilePath.java:747)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class hudson.model.Hudson
	at hudson.scm.SubversionWorkspaceSelector.syncWorkspaceFormatFromMaster(SubversionWorkspaceSelector.java:85)
	at hudson.scm.SubversionSCM.createSvnClientManager(SubversionSCM.java:808)
	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:751)
	at hudson.scm.SubversionSCM$CheckOutTask.invoke(SubversionSCM.java:738)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:1994)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:287)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:60)
	at java.lang.Thread.run(Unknown Source)</p>

<p>As soon as we rollback, we are able again to build the project.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
node: Windows Server 2008 R2, amd64 - Intel64 Family 6 Model 15 Stepping 1, GenuineIntel, jvm 1.6.0_25-b06<br/>
master: AIX
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ilatypov.png" title="ilatypov's avatar" /> ilatypov:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=183665&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-183665">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Also seen with git and gerrit and Jenkins master 1.509.2,</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Retriggered by user ilatypov for Gerrit: http://gerrit.example.net/408143
[EnvInject] - Loading node environment variables.
Building remotely on NODE in workspace /usr/local/jenkins/workspace/PROJECT_Prebuild
Checkout:PROJECT_Prebuild / /usr/local/jenkins/workspace/PROJECT_Prebuild - hudson.remoting.Channel@123d7b31:NODE
Using strategy: Gerrit Trigger
Wiping out workspace first.
hudson.util.IOException2: remote file operation failed: /usr/local/jenkins/workspace/PROJECT_Prebuild at hudson.remoting.Channel@123d7b31:NODE
	at hudson.FilePath.act(FilePath.java:900)
	at hudson.FilePath.act(FilePath.java:877)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:942)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1108)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1367)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:674)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:579)
	at hudson.model.Run.execute(Run.java:1575)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:304)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:237)
	at hudson.model.OneOffExecutor.run(OneOffExecutor.java:66)
Caused by: java.io.IOException: Unable to delete /usr/local/jenkins/workspace/PROJECT_Prebuild/.git/packed-refs
	at hudson.Util.deleteFile(Util.java:256)
	at hudson.Util.deleteRecursive(Util.java:308)
	at hudson.Util.deleteContentsRecursive(Util.java:205)
	at hudson.Util.deleteRecursive(Util.java:299)
	at hudson.Util.deleteContentsRecursive(Util.java:205)
	at hudson.FilePath$12.invoke(FilePath.java:1052)
	at hudson.FilePath$12.invoke(FilePath.java:1049)
	at hudson.FilePath.act(FilePath.java:904)
	at hudson.FilePath.act(FilePath.java:877)
	at hudson.FilePath.deleteContents(FilePath.java:1049)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:958)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:942)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2387)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Retrying after 10 seconds
</pre>
</div></div>

<p>The master runs jdk1.7.0_21, the node runs jdk1.6.0_31 after the master connects to it via SSH.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>[08/14/13 22:27:07] [SSH] Checking java version of java
Couldn't figure out the Java version of java
bash: java: command not found

[08/14/13 22:27:07] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
bash: /usr/bin/java: No such file or directory

[08/14/13 22:27:07] [SSH] Checking java version of /usr/java/default/bin/java
[08/14/13 22:27:07] [SSH] /usr/java/default/bin/java -version returned 1.6.0_31.
[08/14/13 22:27:07] [SSH] Starting sftp client.
[08/14/13 22:27:07] [SSH] Copying latest slave.jar...
[08/14/13 22:27:07] [SSH] Copied 284,251 bytes.
Expanded the channel window size to 4MB
[08/14/13 22:27:07] [SSH] Starting slave process: cd '/usr/local/jenkins' &amp;&amp; /usr/java/default/bin/java  -jar slave.jar
&lt;===[JENKINS REMOTING CAPACITY]===&gt;^@^@^@channel started
Slave.jar version: 2.23
This is a Unix slave
Copied maven-agent.jar
Copied maven3-agent.jar
Copied maven3-interceptor.jar
Copied maven-interceptor.jar
Copied maven2.1-interceptor.jar
Copied plexus-classworld.jar
Copied classworlds.jar
Evacuated stdout
just before slave NODE gets online ...
executing prepare script ...
setting up slave NODE ...
slave setup done.
Aug 14, 2013 10:27:08 PM com.youdevise.hudson.slavestatus.SlaveListener call
INFO: Slave-status listener starting
Aug 14, 2013 10:27:08 PM com.youdevise.hudson.slavestatus.SocketHTTPListener waitForConnection
INFO: Slave-status listener ready on port 3141
[StartupTrigger] - Scanning jobs for node NODE
Slave successfully connected and online
Successfully loaded native POSIX impl.
channel stopped
Connection terminated
[08/14/13 22:28:47] [SSH] Connection closed.
</pre>
</div></div>

<p>The "Connection closed" message in the node log came from my disconnecting the slave via the Jenkins web interface after observing IOException2.</p>
</pre>
</details>

</ul>
</details>

<p>Also seen with git and gerrit and Jenkins master 1.509.2,</p>


```
Retriggered by user ilatypov for Gerrit: http://gerrit.example.net/408143
[EnvInject] - Loading node environment variables.
Building remotely on NODE in workspace /usr/local/jenkins/workspace/PROJECT_Prebuild
Checkout:PROJECT_Prebuild / /usr/local/jenkins/workspace/PROJECT_Prebuild - hudson.remoting.Channel@​123d7b31:NODE
Using strategy: Gerrit Trigger
Wiping out workspace first.
hudson.util.IOException2: remote file operation failed: /usr/local/jenkins/workspace/PROJECT_Prebuild at hudson.remoting.Channel@​123d7b31:NODE
	at hudson.FilePath.act(FilePath.java:900)
	at hudson.FilePath.act(FilePath.java:877)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:942)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1108)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1367)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:674)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:579)
	at hudson.model.Run.execute(Run.java:1575)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:304)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:237)
	at hudson.model.OneOffExecutor.run(OneOffExecutor.java:66)
Caused by: java.io.IOException: Unable to delete /usr/local/jenkins/workspace/PROJECT_Prebuild/.git/packed-refs
	at hudson.Util.deleteFile(Util.java:256)
	at hudson.Util.deleteRecursive(Util.java:308)
	at hudson.Util.deleteContentsRecursive(Util.java:205)
	at hudson.Util.deleteRecursive(Util.java:299)
	at hudson.Util.deleteContentsRecursive(Util.java:205)
	at hudson.FilePath$12.invoke(FilePath.java:1052)
	at hudson.FilePath$12.invoke(FilePath.java:1049)
	at hudson.FilePath.act(FilePath.java:904)
	at hudson.FilePath.act(FilePath.java:877)
	at hudson.FilePath.deleteContents(FilePath.java:1049)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:958)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:942)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2387)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Retrying after 10 seconds

```

<p>The master runs jdk1.7.0_21, the node runs jdk1.6.0_31 after the master connects to it via SSH.</p>



```
[08/14/13 22:27:07] [SSH] Checking java version of java
Couldn't figure out the Java version of java
bash: java: command not found

[08/14/13 22:27:07] [SSH] Checking java version of /usr/bin/java
Couldn't figure out the Java version of /usr/bin/java
bash: /usr/bin/java: No such file or directory

[08/14/13 22:27:07] [SSH] Checking java version of /usr/java/default/bin/java
[08/14/13 22:27:07] [SSH] /usr/java/default/bin/java -version returned 1.6.0_31.
[08/14/13 22:27:07] [SSH] Starting sftp client.
[08/14/13 22:27:07] [SSH] Copying latest slave.jar...
[08/14/13 22:27:07] [SSH] Copied 284,251 bytes.
Expanded the channel window size to 4MB
[08/14/13 22:27:07] [SSH] Starting slave process: cd '/usr/local/jenkins' && /usr/java/default/bin/java  -jar slave.jar
<===[JENKINS REMOTING CAPACITY]===>^@^@^@​channel started
Slave.jar version: 2.23
This is a Unix slave
Copied maven-agent.jar
Copied maven3-agent.jar
Copied maven3-interceptor.jar
Copied maven-interceptor.jar
Copied maven2.1-interceptor.jar
Copied plexus-classworld.jar
Copied classworlds.jar
Evacuated stdout
just before slave NODE gets online ...
executing prepare script ...
setting up slave NODE ...
slave setup done.
Aug 14, 2013 10:27:08 PM com.youdevise.hudson.slavestatus.SlaveListener call
INFO: Slave-status listener starting
Aug 14, 2013 10:27:08 PM com.youdevise.hudson.slavestatus.SocketHTTPListener waitForConnection
INFO: Slave-status listener ready on port 3141
[StartupTrigger] - Scanning jobs for node NODE
Slave successfully connected and online
Successfully loaded native POSIX impl.
channel stopped
Connection terminated
[08/14/13 22:28:47] [SSH] Connection closed.

```

<p>The "Connection closed" message in the node log came from my disconnecting the slave via the Jenkins web interface after observing IOException2.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=243850&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243850">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Don't make sense having this JIRA issue open.</p>
</pre>
</details>

</ul>
</details>

<p>Don't make sense having this JIRA issue open.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/oleg_nenashev.png" title="oleg_nenashev's avatar" /> oleg_nenashev:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=243852&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243852">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Would be useful if you clarify the close reason. Do you think it's unrelated to the plugin? </p>
</pre>
</details>

</ul>
</details>

<p>Would be useful if you clarify the close reason. Do you think it's unrelated to the plugin? </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=243853&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243853">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev" class="user-hover" rel="oleg_nenashev">oleg_nenashev</a> Well, this JIRA was opened on 19/Aug/11. I'm trying to remove all issues related to very old environments and plugin versions. If it is necessary, the JIRA issue author can file another one provinding upgraded information.</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev" class="user-hover" rel="oleg_nenashev">oleg_nenashev</a> Well, this JIRA was opened on 19/Aug/11. I'm trying to remove all issues related to very old environments and plugin versions. If it is necessary, the JIRA issue author can file another one provinding upgraded information.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>lot:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=243876&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243876">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>New features: Yes.
Maintenace and bugfixing: No. It's not fun.</p>

<p>Crap.</p>
</pre>
</details>

</ul>
</details>

<p>New features: Yes.<br/>
Maintenace and bugfixing: No. It's not fun.</p>

<p>Crap.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/recena.png" title="recena's avatar" /> recena:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-10771?focusedId=243889&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243889">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=lot" class="user-hover" rel="lot">lot</a>, What version of Subversion Plugin are you using? Does the bug still continue?</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=lot" class="user-hover" rel="lot">lot</a>, What version of Subversion Plugin are you using? Does the bug still continue?</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `is_duplicated_by` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/10859">JENKINS-10859</a>]</i>
